export interface Citizien {
    uid: string,
    pseudo: string,
    age: number,
    money: number,
    country: string,
    hungry: number,
    health: number,
    social: number,
    intelligence: number,
    cookingSkills: number,
    fitness: number,
    honesty: number,
    love: number,
    kindness: number,
    dailyActionsAvailable: number,
    dailyActionsTotal: number,
    dailyActionsLastDay: number,
    hasEaten: boolean,
    lastEatenPeriod: number
}